esphome:
  name: button-master-left

esp8266:
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esphome-Web-0C5D0E"
    password: "LK2XgXt9rUB0"

captive_portal:

text_sensor:
  - platform: template
    name: Scene Button
    id: scene_button
    lambda: |-
      return {"Released"};
  - platform: template
    name: Scene Button Lights
    id: scene_button2
    lambda: |-
      return {"Released"};      
       
binary_sensor:
  - platform: gpio
    pin:
     number: D2
     mode: INPUT_pullup
     inverted: True
    name: "Scene Button 1"
    internal: true
   
    filters:
     delayed_on_off: 50 ms

    on_multi_click:
    
    - timing:
        - ON for at least 1s
        - OFF for at least 1s
      then:
      - text_sensor.template.publish:
            id: scene_button
            state: "Hold"
      -  delay: 2 s
      - text_sensor.template.publish:
            id: scene_button
            state: "Released"
       
    - timing:
        - ON for at most 0.5s
        - OFF for at least 1s
      then:
        - text_sensor.template.publish:
            id: scene_button
            state: "Clicked"
        -  delay: 2 s
        - text_sensor.template.publish:
            id: scene_button
            state: "Released"
    - timing:
        - ON for at most 0.5s
        - OFF for at most 0.5s
        - ON for at most 0.5s
        - OFF for at least 1s
      then:
      - text_sensor.template.publish:
            id: scene_button
            state: "Double Clicked"
      -  delay: 2 s
      - text_sensor.template.publish:
            id: scene_button
            state: "Released"     
    - timing:
        - ON for at most 0.5s
        - OFF for at most 0.5s
        - ON for at most 0.5s
        - OFF for at most 0.5s
        - ON for at most 0.5s
        - OFF for at least 1s
      then:
       - text_sensor.template.publish:
            id: scene_button
            state: "Tripple Clicked"
       -  delay: 2 s
       - text_sensor.template.publish:
            id: scene_button
            state: "Released"
        
    - timing:
        - ON for at most 0.5s
        - OFF for at most 0.5s
        - ON for at most 0.5s
        - OFF for at most 0.5s
        - ON for at most 0.5s
        - OFF for at most 0.5s
        - ON for at most 0.5s
        - OFF for at least 1s
      then:
         - text_sensor.template.publish:
            id: scene_button
            state: "Fourth Clicked"
         -  delay: 2 s
         - text_sensor.template.publish:
            id: scene_button
            state: "Released"
  - platform: gpio
    pin:
     number: D3
     mode: INPUT_pullup
     inverted: True
    name: "Scene Button 2"
    internal: true
   
    filters:
     delayed_on_off: 50 ms

    on_multi_click:
    
    - timing:
        - ON for at least 1s
        - OFF for at least 1s
      then:
      - text_sensor.template.publish:
            id: scene_button2
            state: "Hold"
      -  delay: 2 s
      - text_sensor.template.publish:
            id: scene_button2
            state: "Released"
       
    - timing:
        - ON for at most 0.5s
        - OFF for at least 1s
      then:
        - text_sensor.template.publish:
            id: scene_button2
            state: "Clicked"
        -  delay: 2 s
        - text_sensor.template.publish:
            id: scene_button2
            state: "Released"
    - timing:
        - ON for at most 0.5s
        - OFF for at most 0.5s
        - ON for at most 0.5s
        - OFF for at least 1s
      then:
      - text_sensor.template.publish:
            id: scene_button2
            state: "Double Clicked"
      -  delay: 2 s
      - text_sensor.template.publish:
            id: scene_button2
            state: "Released"     
    - timing:
        - ON for at most 0.5s
        - OFF for at most 0.5s
        - ON for at most 0.5s
        - OFF for at most 0.5s
        - ON for at most 0.5s
        - OFF for at least 1s
      then:
       - text_sensor.template.publish:
            id: scene_button2
            state: "Tripple Clicked"
       -  delay: 2 s
       - text_sensor.template.publish:
            id: scene_button2
            state: "Released"
        
    - timing:
        - ON for at most 0.5s
        - OFF for at most 0.5s
        - ON for at most 0.5s
        - OFF for at most 0.5s
        - ON for at most 0.5s
        - OFF for at most 0.5s
        - ON for at most 0.5s
        - OFF for at least 1s
      then:
         - text_sensor.template.publish:
            id: scene_button2
            state: "Fourth Clicked"
         -  delay: 2 s
         - text_sensor.template.publish:
            id: scene_button2
            state: "Released"            
